package vn.vanlanguni.ponggame;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


import java.awt.CheckboxGroup;
import java.awt.Color;
import javax.swing.ButtonGroup;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author OS
 */
public class Ten_Nhan_Vat extends javax.swing.JFrame {

    /**
     * Creates new form Ten_Nhan_Vat
     */
//    ButtonGroup checkgroup1;
//    ImageIcon imaball;
//    public Color cl1, cl2;
//
//    ImageIcon ball1 = new ImageIcon("C:\\Users\\OS\\Desktop\\Image ASS 5\\ball 1.png");
//    ImageIcon ball2 = new ImageIcon("C:\\Users\\OS\\Desktop\\Image ASS 5\\ball 2.png");
//    ImageIcon ball3 = new ImageIcon("C:\\Users\\OS\\Desktop\\Image ASS 5\\ball3.png");
//    ImageIcon ball4 = new ImageIcon("C:\\Users\\OS\\Desktop\\Image ASS 5\\ball4.png");
//
//    public Ten_Nhan_Vat() {
//        initComponents();
//        checkgroup1 = new ButtonGroup();
//        checkgroup1.add(jRadioButton1);
//        checkgroup1.add(jRadioButton2);
//        checkgroup1.add(jRadioButton3);
//        checkgroup1.add(jRadioButton4);
//
//        jLabel4.setIcon(ball1);
//        jLabel7.setIcon(ball2);
//        jLabel8.setIcon(ball3);
//        jLabel9.setIcon(ball4);
//        //  jRadioButton1.setIcon(defaultIcon);
//    }
//
//    /**
//     * This method is called from within the constructor to initialize the form.
//     * WARNING: Do NOT modify this code. The content of this method is always
//     * regenerated by the Form Editor.
//     */
//    @SuppressWarnings("unchecked")
//    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
//    private void initComponents() {
//
//        jColorChooser1 = new javax.swing.JColorChooser();
//        nameA = new javax.swing.JTextField();
//        nameB = new javax.swing.JTextField();
//        jLabel1 = new javax.swing.JLabel();
//        jLabel2 = new javax.swing.JLabel();
//        jLabel3 = new javax.swing.JLabel();
//        jLabel5 = new javax.swing.JLabel();
//        jColorChooser2 = new javax.swing.JColorChooser();
//        jButton1 = new javax.swing.JButton();
//        jButton2 = new javax.swing.JButton();
//        jLabel6 = new javax.swing.JLabel();
//        btnsetting = new javax.swing.JButton();
//        jRadioButton1 = new javax.swing.JRadioButton();
//        jRadioButton2 = new javax.swing.JRadioButton();
//        jRadioButton3 = new javax.swing.JRadioButton();
//        jRadioButton4 = new javax.swing.JRadioButton();
//        jLabel4 = new javax.swing.JLabel();
//        jLabel7 = new javax.swing.JLabel();
//        jLabel8 = new javax.swing.JLabel();
//        jLabel9 = new javax.swing.JLabel();
//
//        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
//
//        nameA.addActionListener(new java.awt.event.ActionListener() {
//            public void actionPerformed(java.awt.event.ActionEvent evt) {
//                nameAActionPerformed(evt);
//            }
//        });
//
//        jLabel1.setText("Player One");
//
//        jLabel2.setText("Player Two");
//
//        jLabel3.setText("Ball");
//
//        jLabel5.setText("Color Paddle");
//
//        jColorChooser2.setFocusable(false);
//
//        jButton1.setText("Color 1");
//        jButton1.addActionListener(new java.awt.event.ActionListener() {
//            public void actionPerformed(java.awt.event.ActionEvent evt) {
//                jButton1ActionPerformed(evt);
//            }
//        });
//
//        jButton2.setText("Color 2");
//        jButton2.addActionListener(new java.awt.event.ActionListener() {
//            public void actionPerformed(java.awt.event.ActionEvent evt) {
//                jButton2ActionPerformed(evt);
//            }
//        });
//
//        jLabel6.setText("Press set color for Paddle");
//
//        btnsetting.setText("Apply");
//        btnsetting.addActionListener(new java.awt.event.ActionListener() {
//            public void actionPerformed(java.awt.event.ActionEvent evt) {
//                btnsettingActionPerformed(evt);
//            }
//        });
//
//        jRadioButton1.setSelected(true);
//        jRadioButton1.setFocusable(false);
//        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
//            public void actionPerformed(java.awt.event.ActionEvent evt) {
//                jRadioButton1ActionPerformed(evt);
//            }
//        });
//
//        jRadioButton2.setFocusable(false);
//        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
//            public void actionPerformed(java.awt.event.ActionEvent evt) {
//                jRadioButton2ActionPerformed(evt);
//            }
//        });
//
//        jRadioButton3.setFocusable(false);
//        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
//            public void actionPerformed(java.awt.event.ActionEvent evt) {
//                jRadioButton3ActionPerformed(evt);
//            }
//        });
//
//        jRadioButton4.setFocusable(false);
//        jRadioButton4.addActionListener(new java.awt.event.ActionListener() {
//            public void actionPerformed(java.awt.event.ActionEvent evt) {
//                jRadioButton4ActionPerformed(evt);
//            }
//        });
//
//        jLabel4.setText("jLabel4");
//
//        jLabel7.setText("jLabel7");
//
//        jLabel8.setText("jLabel8");
//
//        jLabel9.setText("jLabel9");
//
//        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
//        getContentPane().setLayout(layout);
//        layout.setHorizontalGroup(
//            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//            .addGroup(layout.createSequentialGroup()
//                .addGap(23, 23, 23)
//                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                    .addComponent(jLabel4)
//                    .addComponent(jRadioButton1))
//                .addGap(60, 60, 60)
//                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                    .addComponent(jRadioButton2)
//                    .addComponent(jLabel7))
//                .addGap(60, 60, 60)
//                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                    .addComponent(jLabel9)
//                    .addComponent(jRadioButton3))
//                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                    .addGroup(layout.createSequentialGroup()
//                        .addGap(60, 60, 60)
//                        .addComponent(jLabel8)
//                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
//                        .addComponent(jLabel6)
//                        .addGap(282, 282, 282))
//                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
//                        .addGap(46, 46, 46)
//                        .addComponent(jRadioButton4)
//                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
//                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                            .addComponent(jLabel5)
//                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
//                                .addGroup(layout.createSequentialGroup()
//                                    .addComponent(jButton1)
//                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
//                                    .addComponent(jButton2))
//                                .addComponent(jColorChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, 429, javax.swing.GroupLayout.PREFERRED_SIZE)))
//                        .addGap(142, 142, 142))))
//            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
//                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                    .addGroup(layout.createSequentialGroup()
//                        .addGap(153, 153, 153)
//                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
//                    .addGroup(layout.createSequentialGroup()
//                        .addGap(134, 134, 134)
//                        .addComponent(jLabel2))
//                    .addGroup(layout.createSequentialGroup()
//                        .addGap(66, 66, 66)
//                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
//                            .addComponent(nameA, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
//                            .addComponent(nameB, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)))
//                    .addGroup(layout.createSequentialGroup()
//                        .addGap(132, 132, 132)
//                        .addComponent(jLabel1)))
//                .addGap(535, 801, Short.MAX_VALUE))
//            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
//                .addGap(0, 0, Short.MAX_VALUE)
//                .addComponent(btnsetting)
//                .addGap(326, 326, 326))
//        );
//
//        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jRadioButton1, jRadioButton2, jRadioButton3, jRadioButton4});
//
//        layout.setVerticalGroup(
//            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//            .addGroup(layout.createSequentialGroup()
//                .addGap(54, 54, 54)
//                .addComponent(jLabel5)
//                .addGap(18, 18, 18)
//                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                    .addGroup(layout.createSequentialGroup()
//                        .addComponent(jLabel1)
//                        .addGap(18, 18, 18)
//                        .addComponent(nameA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
//                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
//                        .addComponent(jLabel2)
//                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
//                        .addComponent(nameB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
//                        .addGap(18, 18, 18)
//                        .addComponent(jLabel3)
//                        .addGap(18, 18, 18)
//                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
//                            .addComponent(jRadioButton1)
//                            .addComponent(jRadioButton2)
//                            .addComponent(jRadioButton3)
//                            .addComponent(jRadioButton4))
//                        .addGap(54, 54, 54)
//                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
//                            .addComponent(jLabel4)
//                            .addComponent(jLabel7)
//                            .addComponent(jLabel9)
//                            .addComponent(jLabel8)))
//                    .addGroup(layout.createSequentialGroup()
//                        .addComponent(jColorChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
//                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
//                        .addComponent(jLabel6)
//                        .addGap(14, 14, 14)
//                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
//                            .addComponent(jButton1)
//                            .addComponent(jButton2))))
//                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
//                .addComponent(btnsetting)
//                .addGap(80, 80, 80))
//        );
//
//        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jRadioButton1, jRadioButton2, jRadioButton3, jRadioButton4});
//
//        pack();
//    }// </editor-fold>                        
//
//    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
//
//        cl1 = jColorChooser2.getColor();
//    }                                        
//
//    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {                                         
//        cl2 = jColorChooser2.getColor();
//    }                                        
//
//    private void btnsettingActionPerformed(java.awt.event.ActionEvent evt) {                                           
//        dispose();
//
//    }                                          
//
//    private void jRadioButton4ActionPerformed(java.awt.event.ActionEvent evt) {                                              
//
//
//    }                                             
//
//    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {                                              
//        imaball = ball2;
//    }                                             
//
//    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                              
//        if (jRadioButton1.isSelected()) {
//            imaball = ball2;
//        }
//    }                                             
//
//    private void nameAActionPerformed(java.awt.event.ActionEvent evt) {                                      
//       
//    }                                     
//
//    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {                                              
//
//    }                                             
//
//    public ImageIcon ballplay() {
//
//        return imaball;
//    }
//
//    public Color changeBGColor() {
//
//        return cl2;
//    }
//
//    public Color changeBGColor2() {
//
//        return cl2;
//    }
//
//    public String nameplayerone() {
//        return nameA.getText();
//    }
//
//    public String nameplayertwo() {
//        return nameB.getText();
//    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ten_Nhan_Vat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ten_Nhan_Vat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ten_Nhan_Vat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ten_Nhan_Vat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ten_Nhan_Vat().setVisible(true);
                new Ten_Nhan_Vat().setSize(1500, 600);
                new Ten_Nhan_Vat().setResizable(false);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton btnsetting;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JColorChooser jColorChooser1;
    private javax.swing.JColorChooser jColorChooser2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JTextField nameA;
    private javax.swing.JTextField nameB;
    // End of variables declaration                   

}
